/* Add games here. Every entry points to one self-contained HTML file in /games. */
const GAMES = [
  { title: 'Super Mario 64', category: 'Engaging', rating: 9.5, verdict: 'Runs beautifully', description: 'A beloved 3D platforming classic in your browser.', image: 'assets/mario64icon.jpg', file: 'games/mario64.html', creditName: 'ArkShocer', creditUrl: 'credits.html#arkshocer' },
  { title: 'Eaglercraft', category: 'Engaging', rating: 2.0, verdict: 'Performance warning', description: 'A blocky browser adventure with a big world.', image: 'assets/eaglercraftIcon.png', file: 'games/eaglercraft.html', creditName: 'PlanetDoge', creditUrl: 'credits.html#planetdoge', warning: true },
  { title: 'dumbLLM', category: 'Apps', rating: 5.0, verdict: 'Performance varies', description: 'A playful local AI experiment made for the launcher.', image: 'assets/dumbLLM.png', file: 'games/dumLLM.html', creditName: 'Digitsofpi314159', creditUrl: 'credits.html#digitsofpi' },
  { title: 'GUST', category: 'Apps', rating: 8.6, verdict: 'Runs great!', description: 'A browser inside a browser, made for curious tabs.', image: 'assets/GUST-logo.png', file: 'games/GUST.html', creditName: 'Nautilus Labs', creditUrl: 'credits.html#nautilus-labs' },
  { title: 'Granny', category: 'Engaging', rating: 8.0, verdict: 'Runs great!', description: 'A tense browser horror classic.', image: 'assets/granny-logo.webp', file: 'games/granny.html', creditName: 'bubbls', creditUrl: 'credits.html#bubbls' },
  { title: 'Basketball Legends', category: 'Engaging', rating: 10.0, verdict: 'Performance warning', description: 'A full-court browser game; may be demanding on some devices.', image: 'assets/basketballLegendsIcon.png', file: 'games/basketballLegends.html', creditName: 'faralong', creditUrl: 'credits.html#faralong', warning: true },
  { title: 'Generic Platformer', category: 'Engaging', rating: 7.0, verdict: 'Runs great!', description: 'A small platforming experiment.', image: 'assets/genericPlatformer3dIcon.png', file: 'games/genericPlatformer.html', creditName: 'Digitsofpi314159', creditUrl: 'credits.html#digitsofpi' },
  { title: 'Donkey Khan', category: 'Engaging', rating: 6.0, verdict: 'Runs great!', description: 'A tiny arcade throwback.', image: 'assets/donkeyKhanIcon.png', file: 'games/donkeyKhan.html', creditName: 'Digitsofpi314159', creditUrl: 'credits.html#digitsofpi' },
  { title: 'Path of Light', category: 'Puzzle', rating: 8.0, verdict: 'Runs great!', description: 'Find the way through a quiet little puzzle.', image: 'assets/pathOfLightIcon.png', file: 'games/pathOfLight.html', creditName: 'Digitsofpi314159', creditUrl: 'credits.html#digitsofpi' },
];
